- .github/workflows/prisma-deploy-dev.yml
Adds a Github Action to deploy prisma schema and seed to the dev server on railway. We might want to remove the `seed data` step when we stop adding new tables/data. Repo secrets will need to be added for this to work.
Tested on a forked repo and a test postgres deployment (DBaaS).
> Github Action to deploy prisma schema

- src/auth/auth.controller.ts
- src/features/features.controller.ts
- src/ideations/ideations.controller.ts
- src/resources/resources.controller.ts
- src/resources/resources.service.ts
- src/teams/teams.controller.ts
- src/techs/techs.controller.ts
- src/users/users.controller.ts
@ApiOperation descriptions added to all controllers. *Some will need to be updated as we update for user auth.
Fixes #40 
Verified all changes appear on Swagger UI.
> @ApiOperation descriptions added to all controllers

- prisma/seed/voyageTeams.ts
- src/teams/dto/update-team-member.dto.ts
Return error if user attempts to enter a number with decimals.
Fixes #47 
I executed PATCH endpoint /teams/3/members/cceec61e-e3dc-4740-ac8b-dbeff70e97e6 _locally via Swagger_ and passed 10.5 as hours and error was returned.
**BEFORE FIX:** I can enter 10.5 hours and return code 200 is returned.
**AFTER FIX:** I try to enter 10.5 hours and error response code 400 is returned.
> Add @IsInt validation to hours per sprint

- .github/workflows/prisma-deploy-dev.yml
- .github/workflows/prisma-deploy-prd.yml
- package.json
Create deployment workflow when pushing to main branch.
Fixes #49 
This will be tested when we push to main branch.
> Create deployment to production workflow

- .husky/pre-push
- package.json
Reverts chingu-x/chingu-dashboard-be#32 - issue with railway deployment
> Revert "add 'postinstall' to enable hooks after install"

- .husky/pre-commit
- package.json
- yarn.lock
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> add husky again

- src/main.ts
Disable swagger in prod for security reason. I've already added NODE_ENV=production in the prod server
> Disable swagger in prod

- src/global/entities/voyage-role.entity.ts
- src/global/responses/shared.ts
- src/global/selects/teams.select.ts
- src/teams/teams.response.ts
- src/users/users.response.ts
- src/users/users.service.ts
Change request by the frontend team - add voyageTeamMemberId to /me and /team/:teamId, so they can match users
Run locally
> Add voyageTeamMember to /me and VoyageTeamMemberID to /team/:teamId

- .github/workflows/prisma-deploy-stg.yml
We are creating a STG environment. This PR is for a new prisma deploy file which will be triggered each time a change is pushed to the stage branch.
Fixes #80
> Add STG prisma github action

- CHANGELOG.md
- src/main.ts
- Add sprint 12 changes to the change log.
- Keep API version to v1 in src/main.ts
_Note: I didn't put the developers name in the changelog. We can do this next sprint, if there is a team concensus to do so._
Fixes #83
> Add changelog

- prisma/seed/users.ts
- prisma/seed/voyage-teams.ts
- prisma/seed/voyage.ts
Update seed data to include a past voyage
will need to manually seed the dev db once approved
Tested locally
> update seed data to include a past voyage

- .github/workflows/prisma-deploy-prd.yml
Add Mailjet api keys variables to prisma-deploy-prd.yml.
> Add mailjet secrets to Github action secrets (PRD)

- .github/workflows/prisma-deploy-stg.yml
Add Mailjet api keys to STG yml file
> Add Mailjet api keys to STG yml file

- prisma/schema.prisma
- prisma/seed/index.ts
- src/HealthCheck/health-check.controller.ts
- test/app.e2e-spec.ts
- test/ideations.e2e-spec.ts
- test/jest-e2e.json
- test/utils.ts
Fixed the ideations tests which broke mainly due to switching from bearer token to http cookies. 
Also a few minor changes
- added `"moduleDirectories": ["<rootDir>/../", "node_modules"]` to fix absolute paths not working with e2e test files
- close app when finished to avoid openHandles
- restrcuture seed file, so the seed() function can be called from within the code (for e2e testing)
`yarn test:e2e`
> Fixed all failed tests (app, ideation)

- .github/pull_request_template.md
- CHANGELOG.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
previewed locally
not applicable as this PR is a MD file change only
> update pull request template and change log for last 2 PRs

- .github/workflows/test.yml
- CHANGELOG.md
- prisma/schema.prisma
Add e2e tests to test workflow, when pull request target is main
Tested on my fork -
> Add e2e tests to test workflow (on PR to main branch)

- CHANGELOG.md
- src/app.module.ts
- src/resources/resources.controller.ts
This PR will change the URI for Resources PATCH and DELETE endpoints to the following:
- PATCH voyages/{teamId}/resources/{resourceID} => voyages/resources/{resourceId}
- DELETE voyages/{teamId}/resources/{resourceID} => voyages/resources/{resourceId}
Fixes [Update resources patch and delete uri task on clickup](https://app.clickup.com/t/86azvtjkd)
This can be tested by confirming by running `yarn start:dev` and checking in swagger UI that the URIs are correct for PATCH and DELETE endpoints in Resources.
Also the unit test and e2e test can be ran to make sure everything still works.
> Update resources patch and delete uri

- CHANGELOG.md
- prisma/seed/forms/checkinform.ts
- prisma/seed/sprints.ts
- prisma/seed/users.ts
- prisma/seed/voyage-teams.ts
- prisma/seed/voyage.ts
- src/ability/conditions/voyage-teams.ability.ts
- src/ideations/ideations.service.spec.ts
- test/sprints.e2e-spec.ts
- Update Seed data to include v48 to v51 also update the dates according to the this https://suwanna.atlassian.net/wiki/spaces/SD/pages/81330178/Timezones
- This document shows all the test teams and members
https://suwanna.atlassian.net/wiki/spaces/SD/pages/82378754/Test+Teams+and+Users
- Also updated "own_team" permission check to bypass admins
- had to fix a few tests
- We will need to reseed dev server database after this is merged
https://app.clickup.com/t/86b0cupn5
ran `prisma db seed` to verify the seeding works
> Update seed files to include v48-51

- CHANGELOG.md
- src/users/users.controller.spec.ts
- src/users/users.service.spec.ts
This PR provides unit tests for the controller and services in the users folder. 
Fixes #[86azu6kvp](https://app.clickup.com/t/86azu6kvp)
Test by running `yarn test:unit` or `yarn test:unit:docker` with `users` to the unit tests for users' controller and service files.
check if the unit tests meet all that is required from the [unit tests wiki page](https://github.com/chingu-x/chingu-dashboard-be/wiki/Tests#unit-tests)
> tests(users): unit tests for user controller and services

- CHANGELOG.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> update changelog for alpha release

- prisma/seed/forms/checkinform.ts
This PR revises two check in questions:
What is your role on the team? - removed
anyone deserves a shout out? - changed to input type teamMemberCheckBox
-waiting for new changelog file
Fixes # [86b1yhjy1](https://app.clickup.com/t/86b1yhjy1)
yarn seed, verified in Prisma Studio
> Revise question forms

- CHANGELOG.md
> updated changelog for pr 192

- CHANGELOG.md
- prisma/seed/users.ts
- prisma/seed/voyage-teams.ts
- prisma/seed/voyage.ts
- Created `2 new users` and voyage `52` and `53`
- Added team `v52-tier1-team-1` to have only `PO` with   `memberId `as `41` and `42`
- Added team `v52-tier1-team-2` to have only `SM`  with `member Id`  `43` and `44`
- Added team `v52-tier2-team-2` to have  `3 developers` with `memberId` `45`, `46` and `47`
- Added team `v52-tier2-team-4`  to have    `1 UI/UX designer`  , `1 data scientist` and `1 voyage guide`  having `memberId `as `48`, `49` and `50`
- Added team `v52-tier3-team-3`  to have  all roles `1 SM`, `1 PO`,` 3 developers`, `1 UI/UX designer` , `1 data scientist`  and `1 voyage guide` having `memberId `as  `51`  , `52`, `53`, `54`, `55`, `56`, `57` and `58`
[Fixes # (issue)](https://app.clickup.com/t/86b27xvk2)
- tested with `yarn seed`
- tested with `yarn test:docker`
> chore: update user voyage roles in dev seed

- CHANGELOG.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Update CHANGELOG.md for new release

- CHANGELOG.md
- src/development/development.controller.ts
- test/development.e2e-spec.ts
-  Updated the endpoint  `database/reseed` to allow execution without logging in
[Fixes # (issue)](https://app.clickup.com/t/86b32pe1d)
- Tested in Swagger
> Update: Reseed endpoint to public
