.husky/common.sh, .husky/pre-push, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dto/login.dto.ts, src/auth/local.strategy.ts, src/features/features.controller.ts, src/features/features.service.ts, src/resources/resources.service.ts
Add body to swagger so frontend doesn't have to login with postman or equivalent, which means it would also add cookie to the swagger browser
I also had to add the windows code for husky (after I "fixed" husky locally) otherwise I can't push at all, see #32 
tested locally
=> Add body to swagger for login endpoint

.github/workflows/prisma-deploy-dev.yml, .github/workflows/prisma-deploy-prd.yml, .github/workflows/prisma-deploy-stg.yml, .github/workflows/test.yml
Jest tests are failing on deploy to main branch because Mailjet API keys are missing from yml file.
- Add MJ_APIKEY_PUBLIC and MJ_APIKEY_PRIVATE secrets entries to test.yml file.
- Remove MJ_APIKEY_PUBLIC and MJ_APIKEY_PRIVATE from deploy prisma yml files since they were added there incorrectly.
=> Remove Mailjet api keys secrets from deploy files and add to test.yml

CHANGELOG.md, package.json, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dto/signup.dto.ts, src/utils/emails/sendEmail.ts, test/auth.e2e-spec.ts, test/utils.ts, yarn.lock
Add e2e tests for auth controllers. There are also a few adjustments like
- not actually sending email when doing tests
- making password min 8 chars
- added logger for auth service instead of console.log
- added a few undocumented api responses
`yarn test:e2e auth`
=> Auth controller e2e tests

CHANGELOG.md, src/ideations/ideations.controller.spec.ts, src/ideations/ideations.service.spec.ts, src/ideations/ideations.service.ts
Fix this issue https://github.com/chingu-x/chingu-dashboard-be/pull/120#issuecomment-2015098016 from PR #120 
I was looking at the wrong tests (e2e), it was the unit tests which had issues. Thanks @timDeHof
=> Fix unit tests where mocked req doesn't match new CustomRequest type

CHANGELOG.md, src/resources/resources.response.ts, src/resources/resources.service.ts
This PR modifies the return body of GET `voyages/teams/{teamId}/resources`, adding the user id value to the addedBy property. 
Tested in swagger
=> Updated Resources GET response, added user id value

CHANGELOG.md, src/auth/strategies/at.strategy.ts, src/users/users.service.ts
Added optional chaining in two places
Fixes [Auth - cannot read roles on server startup](https://app.clickup.com/t/86b031fb3)
=> Fix bug "Auth - cannot read roles on server startup"

CHANGELOG.md, src/techs/techs.controller.ts, src/techs/techs.response.ts, src/techs/techs.service.ts, test/techs.e2e-spec.ts
This PR will rename the id property in the TechItemResponse class to teamTechStackItemVoteId to provide better clarity and improve semantics. The example value for the teamMemberId property has been updated to 8 to maintain consistency with other example values. The create method in the TechsService class now returns an object that includes the teamTechStackItemVoteId property for consistency. Similarly, the delete method now returns an object that includes the teamTechStackItemVoteId property for consistency.
Fixes # [https://app.clickup.com/t/86azw0fjm](https://app.clickup.com/t/86azw0fjm)
In swagger:
1. run `POST /api/v1/auth/login`
2. After a successful login, run `POST /api/v1/voyages/teams/{teamId}/techs/{teamTechId}` with 'teamId: 2' and 'teamTechId: 6'. I found these two …
=> Update response Ids - POST voyages/teams/teamId/techs

CHANGELOG.md, src/sprints/sprints.response.ts, src/sprints/sprints.service.ts
This PR updates the response body for route GET `sprints/meetings/{meetingId}`
The 200 response now includes an `updatedAt` Date value for each item in the agendas array
No e2e tests were affected by this change
[Fixes # (86b071e68)](https://app.clickup.com/t/86b071e68)
Tested in swagger:
E2e tests:
`yarn test:e2e sprints`
=> Sprint meetings -  updatedAt

.github/workflows/test.yml, CHANGELOG.md
Adding timeout since last failed run was 6h long which is using up github actions quota. A normal run is around 6-9mins
Tested on my forked
- x] I have commented my code, particularly in hard-to-understand areas
=> Add 30min timeout to github actions test workflow

CHANGELOG.md, prisma/seed/data/input-types.ts, prisma/seed/forms/checkinform.ts, prisma/seed/forms/voyage-project-submission.ts, prisma/seed/responses/helper.ts
Added some form input types to make it easier for frontend to render the display
Please check this document out on confluence for descriptions of all input types 
https://suwanna.atlassian.net/wiki/spaces/SD/pages/79888385/Input+Types
https://app.clickup.com/t/86b0ab2dh
ran `prisma db seed` with no error
=> Update form input types

CHANGELOG.md, prisma/seed/forms/index.ts, prisma/seed/meetings.ts, prisma/seed/solo-project.ts, prisma/seed/voyage-app.ts, src/sprints/sprints.service.ts, test/sprints.e2e-spec.ts
All the form title reference are updated to use  the values in the file formTitle.ts
https://app.clickup.com/t/86azvdyff
- Performed unit tests
- Performed  e2e tests
=> Refractor: update all form title reference

CHANGELOG.md, src/features/features.controller.ts, src/features/features.response.ts, src/features/features.service.ts
This pull request introduces a new DeleteFeatureResponse class to handle the response for feature deletion scenarios. The class includes a message and statusCode property, which will provide a consistent and clear response when deleting a feature.
The deleteFeature method in the FeaturesService has also been updated to return an instance of the newly added DeleteFeatureResponse class. When a feature is successfully deleted, the method will return a response object with a success message and a status code of 200.
Fixes # [https://app.clickup.com/t/86b07bdar](https://app.clickup.com/t/86b07bdar)
Since the features don't have any tests for them yet. you have to test this endpoint in swagger by login as the default user and type `7` for the featureId, which should give a 200 response status …
=> Introduce DeleteFeatureResponse and update deleteFeature method with a status code and a message 

CHANGELOG.md, prisma/seed/forms/voyage-project-submission.ts, prisma/seed/responses/helper.ts, prisma/seed/sprints.ts, prisma/seed/utils/index.ts, prisma/seed/voyage.ts
Update seed files 
- add 'url' input type
- add time to sprint end dates and deadlines
[Fixes # (issue)](https://app.clickup.com/t/86b0cc5r2)
=> Update seed data (url input type, end date time)

CHANGELOG.md, README.md, package.json
changed `yarn test` (and the docker equivalent) to `yarn test:unit` and repurpose `yarn test` (and `yarn test:docker`) to run both unit and e2e test and suppress all console.log. We can also add integration tests and coverage later on 
[Fixes # (issue)](https://app.clickup.com/t/86azu6j31)
tested on docker and non docker setup
=> update yarn test command

CHANGELOG.md, src/global/global.service.ts, src/pipes/form-input-validation.ts, src/sprints/dto/create-checkin-form.dto.ts, src/sprints/sprints.service.ts
When response is false, the validation pipe returns an error and the boolean value is also not inserted into the database properly
This is a new PR after renaming #154 as the branch name was causing issue for some members
[Fixes # (issue)](https://app.clickup.com/t/86b0e28ea)
ran all the tests, send request from swagger and verified the values in the database
=> Fix form responses giving error and not inserting values when the boolean value is false

CHANGELOG.md, src/sprints/sprints.controller.ts, test/sprints.e2e-spec.ts
This PR adds a standard 401 response for all Sprints endpoints, when the user is not logged in.  These changes are shown in the swagger documentation and in e2e tests for all routes
Fixes # [86azuu45a](https://app.clickup.com/t/86azuu45a)
Verified in swagger and in sprints e2e tests
=> Added 401 responses to sprints endpoints and swagger docs

CHANGELOG.md, src/pipes/voyage-team-member-validation.ts, src/sprints/sprints.controller.ts, test/sprints.e2e-spec.ts
- Added custom validation pipe for voyage team member id in the request body
- It restricts the check-in submission from arbitrary member ids 
- Added e2e test for `api/v1/voyages/sprints/check-in`    
[Fixes # (issue)](https://app.clickup.com/t/86b0d9age)
It passes all the existing and new tests. It is tested with swagger  for desired output
=> Bug: no check on voyage team member

CHANGELOG.md, prisma/seed/data/form-types.ts, src/ability/ability.factory/ability.factory.ts, src/ability/conditions/forms.ability.ts, src/ability/conditions/voyage-teams.ability.ts, src/ability/prisma-generated-types.ts, src/auth/auth.controller.ts, src/forms/forms.controller.ts, src/forms/forms.service.ts, src/global/constants/formTypeId.ts, src/main.ts, src/sprints/sprints.controller.ts, src/sprints/sprints.service.ts, src/teams/teams.controller.ts, test/forms.e2e-spec.ts
Updated swagger endpoint descriptions for auth, and forms
Add permission to forms
Only part of the task as I don't want the PR to get to big
CASL notes for reference: https://suwanna.atlassian.net/wiki/spaces/SD/pages/76349451/CASL
Issues: 
It seems prisma/casl doesn't support matching nested values (https://casl.js.org/v5/en/guide/conditions-in-depth#match-nested-property-value)
so I have used a workaround instead
https://app.clickup.com/t/86azr0q42
Tested on swagger, and `yarn test:docker`
=> Add swagger access info and form endpoint permissions

CHANGELOG.md, src/ideations/ideations.service.ts, test/ideations.e2e-spec.ts
This PR updates the DELETE `voyages/teams/{teamId}/ideations/{ideationId}/ideation-votes` route to also delete the corresponding ideation, if there are no more votes for it.
Notes:
Functions `deleteIdeation` and `deleteIdeationVote` have been refactored to avoid conflicting with each other 
Upated e2e tests to check deletion of ideation when last vote is deleted
Fixed conflicts with other tests
Fixes # [86b0fw6kn](https://app.clickup.com/t/86b0fw6kn)
In swagger: Login, post vote for team 1, ideation 1
In Prisma Studio: delete original projectIdeaVote (id: 1)
In Swagger: delete vote for team 1, ideation 1
Check results in Studio: no projectIdeaVotes for 1 , no projectIdea 1
Tests:
`yarn test:e2e ideations`
=> Delete ideation vote and ideation

CHANGELOG.md, src/teams/teams.controller.ts, src/teams/teams.service.ts, test/teams.e2e-spec.ts
- Added e2e tests for Teams controller
[Fixes # (issue)](https://app.clickup.com/t/86azr0q4g)
Tested with `yarn test:docker`
=> Test: e2e test for teams

CHANGELOG.md, src/features/dto/update-feature.dto.ts, src/features/features.controller.ts, src/features/features.service.ts, test/features.e2e-spec.ts
- e2e test for `features controller`
[Fixes # (issue)](https://app.clickup.com/t/86azr0q4j)
- tested with  `yarn test:docker`
=> Test: e2e tests for features

CHANGELOG.md, prisma/seed/forms/checkinform.ts, prisma/seed/forms/checkinformPO.ts, prisma/seed/forms/checkinformSM.ts, prisma/seed/forms/index.ts, src/global/constants/formTitles.ts
This PR add checkin forms that ask team members for feedback on Product Owners and scrum masters that are on their teams.  
- Two new form titles, "Sprint Check-in (Product Owner)" and "Sprint Check-in (Scrum Master)", have been added to the FormTitles constant. 
- Two new forms, `checkinformPO.ts` and `checkinformSM.ts`, have been added to the `prisma/seed/forms` folder.
Fixes # [add more checkin forms](https://app.clickup.com/t/86b0rfhc6)
I tested this by:
1. run `yarn seed` to populate the database
2. run `yarn studio` and look in the form for "Sprint Check-in (Product Owner)" and "Sprint Check-in (Scrum Master)" in the title section
3. in the form, the "Sprint Check-in (Product Owner)" form should show `2` questions and "Sprint Check-in (Scrum Master)" should show `4` questions.
=> Feat: Add more checkin form and updates base checkin form questions

CHANGELOG.md, src/HealthCheck/health-check.controller.ts, src/app.module.ts, src/development/development.controller.spec.ts, src/development/development.controller.ts, src/development/development.module.ts, src/development/development.response.ts, src/development/development.service.spec.ts, src/development/development.service.ts, src/global/responses/errors.ts, src/voyages/voyages.controller.spec.ts, src/voyages/voyages.service.spec.ts, test/development.e2e-spec.ts
Add an endpoint so we can reseed the database using the API. It will only proceed if NODE_ENV=development. Added e2e tests and unit tests
https://app.clickup.com/t/86b0xdy8e
Tested on swagger and `yarn test:docker`
=> Add endpoint for database reseed

CHANGELOG.md, src/ability/ability.factory/ability.factory.ts, src/ability/conditions/ideations.ability.ts, src/app.module.ts, src/ideations/ideations.controller.spec.ts, src/ideations/ideations.controller.ts, src/ideations/ideations.service.spec.ts, src/ideations/ideations.service.ts, test/ideations.e2e-spec.ts
Remove teamId params from 
`PATCH /voyages/ideations/{ideationId}`
`DELETE /voyages/ideations/{ideationId}`
`PATCH /voyages/ideations/{ideationId}/ideation-votes`
`DELETE /voyages/ideations/{ideationId}/ideation-votes`
https://app.clickup.com/t/86b0ump7x
Tested manually on swagger and ran `yarn test:docker`
=> Refactor ideation endpoints to remove redundant teamId params

CHANGELOG.md, prisma/seed/forms/checkinformPO.ts, prisma/seed/forms/checkinformSM.ts, prisma/seed/voyage-teams.ts
- Updated the question order in SM and PO check-in form 
- For PO it starts from `101`  and for SM it starts from `201`
- Changed the `voyage-role` of one of the member from `team 6` to `PO`
[Fixes # (issue)](https://app.clickup.com/t/86b1zvbaw)
https://github.com/chingu-x/chingu-dashboard/issues/216
- tested with `yarn test:docker`
-  tested with `yarn seed`
=> chore: update check-in form SM and PO and change voyage-role[216]

CHANGELOG.md, src/features/features.service.ts, test/features.e2e-spec.ts
- Members of the same team can update the order and category of the features
- Removed the check for `memberId `  and replaced it with `teamId`
- Added a e2e test for the above change
[Fixes # (issue)](https://github.com/chingu-x/chingu-dashboard/issues/253)
- tested with `yarn test:docker`
-  tested with `swagger`
=> Bug: add check for team id in place of memberId

CHANGELOG.md, src/sprints/sprints.controller.ts, src/sprints/sprints.service.ts
GET Voyage/Sprints/Teams/{TeamId} was pulling all TeamMeetings for the voyage the team is in, instead of team specific teamMeeting Ids.
Return structure was kept the same so minimal change is required.
This may or may not fix https://github.com/chingu-x/chingu-dashboard/issues/264
No task on clickup, as it just came up and fixed it while investigating
More detail here - https://docs.google.com/document/d/1K-xjyYnOAEUROHDXCARpX7okleW3S5BYf05f7Sb0k_E/edit?usp=sharing
checked manually on swagger and ran the tests
=> Fix/voyage sprints get teamid 

CHANGELOG.md, src/auth/auth.module.ts, src/development/development.module.ts, src/tasks/tasks.module.ts, test/app.e2e-spec.ts, test/development.e2e-spec.ts, test/features.e2e-spec.ts, test/jest-e2e.json, test/teams.e2e-spec.ts, test/unverifiedUser.e2e-spec.ts, test/users.e2e-spec.ts
The import paths are changed to use the alias '@/' instead of relative paths. This improves code readability and maintainability by making it easier to understand the structure of the project and reducing the complexity of navigating through nested directories.
Fixes [Make e2e imports (and other imports) work with paths/absolute inputs](https://app.clickup.com/t/86b2346xp)
You test this PR by running the command `yarn test:e2e` or `yarn test:e2e:docker`, which all tests should pass.
If we want I could work adding absolute paths to the unit tests too. Let me know in the comments.
=> refactor: changed E2E import paths to use '@/' 

CHANGELOG.md, src/main.ts
Current CORS origin entry for localhost is wrong - `http://localhost:*` does not match all port, its just a static string, we need to use regex
-
tested on a dummy next.js client component (as CORS has no effect on server components)
=> Fix CORS origin localhost entry

.github/workflows/pr-reviwer-reminder.yml, CHANGELOG.md
Add github workflow for PR reminder
- [] My code follows the style guidelines of this project
=> Add github workflow for PR reminder

CHANGELOG.md, src/auth/auth.service.ts
I'm having trouble getting a screenshot for this but basically there is an issue with the cookies and cross-site domains so we need to set the same-site as none. Adding that fixed this issue
This is probably only an issue with client components but since we are gunna have a separate react project in the future (which would be client) that'll communicate with this backend, this would fix for that usecase as well
I ran into this issue when trying to test from localhost on frontend and the deployed backend dev server.
I also ran into this issue using localhost on the backend and the preview deployed url on vercel (it's using the localhost backend, just different domain).
After implementing this, it worked as expected
=> add same site property to cookie

CHANGELOG.md, docker-compose.yml
Update docker compose to use Timescaledb/pg16 - which allows backup/restore between deployed db on railway 
`yarn docker --build`, `yarn push`, `yarn seed` everything ran fine, checked on swagger as well
=> Update docker compose to use timescaledb

CHANGELOG.md, src/auth/auth.controller.ts, src/auth/auth.service.ts
I have no idea why I didn't run into this issue before. Gotta love dev work sometimes. 
The refresh endpoint needs to have the same site property added as well and I fixed that in this pr. 
Could maybe look into refactoring it but I'll leave that to BE team.
Also, I'm not sure if it was intentional to add a new refresh token cookie too in the refresh endpoint?
I tested with localhost on backend and a deployed url in vercel. I did this in last pr too but for whatever reason this issue didn't come up last time. But it is working again with this fix.
https://chingu-dashboard-git-feature-refreshtoken-chingu-dashboard.vercel.app/dashboard
=> add same site property to the cookie sent in the refresh endpoint

CHANGELOG.md, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/main.ts
Added same site to the logout method (where cookies are cleared).
Also ran into an issue with cors again. I updated the list to account for numbers and underscores.
I tested with localhost on the backend and in vercel preview deployment
https://chingu-dashboard-git-refactor-auth-arch-a87d55-chingu-dashboard.vercel.app/dashboard
=> add same site property to logout method and update cors origin list

CHANGELOG.md, src/features/features.controller.spec.ts, src/features/features.service.spec.ts, src/features/features.service.ts
- Unit tests for `Feature controller and Services`
[Fixes # (issue)](https://app.clickup.com/t/86azu6kw4)
- tested with  `yarn test:docker`
=> Test: unit test for features controller and services

CHANGELOG.md, src/techs/dto/update-tech-selections.dto.ts, src/techs/techs.controller.ts, src/techs/techs.service.ts, test/techs.e2e-spec.ts
- This PR revises the PATCH /teams/techs/:techId route to only update a single tech stack selection, setting the `isSelected` value
- Also, a permission bug has been fixed for POST /teams/{teamId}/techs , ensuring users can only add a new tech for thier own team
Fixes # [86b1ym631](https://app.clickup.com/t/86b1ym631)
- migrate db for updates
- yarn test
=> Update tech selections

.github/workflows/release-please.yml, CHANGELOG.md
Create Release please yml file. The changes probably won't take effect till after next time we merge into main. It has been tested on my fork repo. We will need to make sure we start using squashed, conventional commits. 
Fork: https://github.com/cherylli/chingu-dashboard-be/pulls
Release please: https://github.com/googleapis/release-please
Conventional commits: https://www.conventionalcommits.org/en/v1.0.0/
Squashing commits: 
https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together
https://github.com/chingu-x/chingu-dashboard-be/wiki/Getting-Started
We will still maintain the changelog in the period of transition, till we completely follow conventional commits
Updated Wiki: https://github.com/chingu-x/chingu-dashboard-be/wiki/Getting-Started …
=> Chore: setup release please

prisma/migrations/20250216074419_update_user_schema/migration.sql, prisma/schema/user.prisma, src/global/selects/users.select.ts, src/users/entities/user.entity.ts, src/users/users.service.spec.ts, src/users/users.service.ts
-  Added `emailVerified`  field in the response  to check if the user is verified.
-  Added `hasCompletedAssessment` field to User schema to check for  completion of assessments.
- Added  `soloProjects` array containing `id`  and `status` to the response 
[Fixes # (issue)](https://app.clickup.com/t/86b3uam3x)
- Tested using `Swagger`  to receive the checklist items in  `/me `  endpoint
- Tested  with  `yarn  test:docker`  to pass all the e2e and unit tests
=> Feat: added new user checklist items 

src/forms/forms.response.ts, src/forms/forms.service.ts, src/global/dtos/FormResponse.dto.ts, src/global/mocks/mock-data.ts, src/sprints/sprints.controller.spec.ts, src/sprints/sprints.response.ts, src/sprints/sprints.service.spec.ts, src/sprints/sprints.service.ts
Added support for adding the `parseConfig` field to fetching of form questions configuration, along with flexibility. This new optional field allows for additional configuration parameters to be stored for different question types, such as:
- Icon-based radio buttons
- Scale questions with custom min/max labels
- Boolean questions with custom yes/no text
In addition, A new wiki page was created called [Form Input types v2](https://github.com/chingu-x/chingu-dashboard-be/wiki/Form-Input-types-v2)
The changes include:
1. Added `parseConfig` field to `OptionChoice` and `BaseQuestion` classes
2. Updated form selection queries to include the new field
3. Added proper validation and Swagger documentation
Fixes # [86b3u7ygj](https://app.clickup.com/t/86b3u7ygj)
The changes have been tested …
=> feat: Multiple Parse Options support Stage1b - Add parseConfig to forms response and service models

.github/workflows/test.yml
update node version to 22 in lint and test workflow
Fix #249 failing test and lint workflow due to node version being too low
Tested on my fork - https://github.com/cherylli/chingu-dashboard-be/actions/runs/14008118704/job/39224526712?pr=11
=> chore: (github actions) update node version from 18 to 22
